[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
atlas_dungeon = "EZ3Rap3QF8yrngyfRCZfziNDxb5PkWiQXAMJwS9vcb3t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"